### ISSUE TITLE
Finish the game

### ISSUE THREAD

**Issue by nasivuela** [Adalab/f-m2-evaluacion-intermedia-mirenguerra#1]
Cool job @mirenguerra !!! You are almost there.

Here you have some tips to finish the game:

- [x] Remove max param from 'getRandomNumber 'function if you aren't going to use it.
- [x] Remember to convert input value to number to be able to compare it with 'aleatoryNumber'
- [x] Define the logic to make the counter work.
- [x] Do not use 'preventDefault' when the element and the event used do not have a default behavior to prevent
- [x] Move variables declaration to the top of the file
- [x] Indent and avoid extra white spaces to improve readability and prevent bugs
- [x] Connect the label to the input using the `for` attribute of the label and the `id` of the input

Let me know if you have any doubts ;)

Go for it!!

**Comment by mirenguerra** [comment]
Hi @nasivuela !!

I have finished the exercise following your tips and I have tried to improve it a bit.

I have included a .svg and a spinner in the counter.
I have limited the counter so that the content does not leave the spinner and added different feedback messages according to the value you put in the input.
I have created a button to play again that appears when you win, but I still can't get the counter to start over from scratch. Could you give me some tip for this?
I'm also thinking about making the frog jump, move or something (I don't know what yet) when you win.

This exercise really stayed in me!!, 

Thank you very much for your feedback.

**Comment by mirenguerra** [comment]
@nasivuela with gulp my exercise looks good but building docs, in GitHubPages doesn't work well. any idea why it can be?

Thanks!

**Comment by nasivuela** [comment]
Awesome work @mirenguerra !!! Such a cute frog ;)

About your doubts:
- I see it perfectly on Github Pages.
- When you reset the game, you are replacing the value of the counter on HTML, but what about the variable counter on js? A good approach would be to reset the value of the counter variable, and put it in testCounterEl.innerHTML, as you are doing in each try.

Here you have more improvements to continue practicing

- [x] Move the feedback logic to a function an execute it on each click
- [x] Move you counter logic into a function and execute it on each click
- [x] You are writing many times "testFeedbackEl.innerHTML = 'something';", what about making a function that accepts a string as param and paints it into 'testFeedbackEl'?
- [x] Clean it a little removing comments and console.logs

Once you add the improvements I will close the issue, but  you also can continue and:

- Make the input work when hitting the enter key.
- Make you little frog mobile friendly 
- Whatever you want!

Go for it!

**Comment by mirenguerra** [comment]
Hi @nasivuela !


I am very proud to teach you my exercise.

I've followed all your tips and I've also added some improvements such as limiting the use of float numbers, (cause parseInt rounded that numbers and a false win comes out), add a function when you win and I've made the frog jump!

I think I have learned a lot with this exercise and I want to continue improving with the new things I learn. I'm very happy! 

If you think I can do some improvement, please tell me! Thanks!!

**Comment by nasivuela** [comment]
O_O

Super cool!!!

PD. try to use **strict** comparison operators (=== and !==)

![](https://media.giphy.com/media/iwqJk8sFdwcxy/giphy.gif)
